title: Hi
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jojuyoung2171.github.io"
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Jojuyoung
tagline: Yong moon student
about-description: Photos of Kyoto, Thank you for watching! 
pic: japan.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: jojuyoung2171@gmail.com # Add your Email address
phone: 123 4567 8910 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
linkedin: https://www.youtube.com/
github: jojuyoung2171 # Add your Github handle
instagram: '@jojuyoung2171' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
